### ISSUE TITLE
MIUI Security and Settings Mod for Android 13

### ISSUE THREAD

**Issue by Foxydroid** [reiryuki/Miui-Security-Magisk-Module#5]
Will there be modules for android 13? Since when installing a bootlap, I suppose due to compatibility. If it's not difficult for you, please write 😊

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except AML)
4) Full logcat #logcat
5) Z folder #zscript

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
