### ISSUE TITLE
Poco X3 Pro Bootlooping

### ISSUE THREAD

**Issue by Foxydroid** [reiryuki/Miui-Security-Magisk-Module#6]
My Poco X3 Pro won't work beyond the loading screen. Firmware Evolution OS. Android 13.
Link to logs and Z-script: [Click](https://drive.google.com/file/d/16iExL-Af6jXCSfmDPVCF6TsvJ_TKZjcT/view?usp=drivesdk)

**Comment by reiryuki** [comment]
Try the latest version
this issue will be closed if no answer in 24 hours
