### ISSUE TITLE
MIUI Security Crashes

### ISSUE THREAD

**Issue by xChAmeLIoNz** [reiryuki/Miui-Security-Magisk-Module#9]
Hello,

I've been trying to use this module because my xiaomi mi pad 5 has an issue with hdr (dark scenes are too dark), and the only "fix" for this was to enable the "outdoor mode" found in the miui video toolbox (which apparently resides in this module).
Before flashing this module, I **disabled** all the other modules that were active, as a precaution.
The module doesn't seem to be working, as when I try to launch it, it immediately crashes.

Below I provide all the required files and folder such as magisk install log, full logcat log (all buffers enabled) and the zipped "z" folder.
I hope this can help to fix this issue and feel free to ask me any further information.

[logcat_05-24-2023_21-03-57.txt](https://github.com/reiryuki/Miui-Security-Magisk-Module/files/11558266/logcat_05-24-2023_21-03-57.txt)
[magisk_install_log_2023-05-24T20.56.35.log](https://github.com/reiryuki/Miui-Security-Magisk-Module/files/11558268/magisk_install_log_2023-05-24T20.56.35.log)
[z.zip](https://github.com/reiryuki/Miui-Security-Magisk-Module/files/11558269/z.zip)

**Comment by reiryuki** [comment]
update to v1.13

**Comment by xChAmeLIoNz** [comment]
> update to v1.13

I can see Video Toolbox in MIUI Security but it doesnt show up in the selected applications.
Is there something additional required to make it work?
